// Copyright (C) 2024 Guyutongxue
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import { glob } from "glob";
import path from "node:path";
import { writeFile } from "node:fs/promises";
import { BASE_PATH, LICENSE } from "./config";

const TARGET = path.join(BASE_PATH, "index.ts");
const GLOB = path.join(BASE_PATH, "**/*.ts");

export async function generateImports() {
  const files = (await glob(GLOB, {
    ignore: `${BASE_PATH}/*.ts`,
    windowsPathsNoEscape: true,
  })).toSorted();

  function pathToImport(path: string) {
    return path
      .replace(/\.ts$/, "")
      .replace(/\\/g, "/")
      .replace(new RegExp("^" + BASE_PATH, "g"), ".");
  }

  const imports = files.map((f) => `import "${pathToImport(f)}";`).join("\n");

  await writeFile(
    TARGET,
    `${LICENSE}// Generated by scripts/generators/imports.ts
// DO NOT EDIT

import "./begin";

${imports}

export { default } from "./end";
`,
  );
}
