import { glob } from "glob";
import path from "node:path";
import { writeFile } from "node:fs/promises";
import { BASE_PATH } from "./config";

const TARGET = path.join(BASE_PATH, "index.ts");
const GLOB = path.join(BASE_PATH, "**/*.ts");

export async function generateImports() {
  const files = await glob(GLOB, {
    ignore: TARGET,
    windowsPathsNoEscape: true,
  }).then((files) => files.sort());

  function pathToImport(path: string) {
    return path
      .replace(/\.ts$/, "")
      .replace(/\\/g, "/")
      .replace(new RegExp("^" + BASE_PATH, "g"), ".");
  }

  const imports = files.map((f) => `import "${pathToImport(f)}";`).join("\n");

  await writeFile(
    TARGET,
    `// Generated by scripts/generators/imports.ts
// DO NOT EDIT

${imports}
`,
  );
}
