export const GITCG_ATTR_INIT_DATA_VERSION = 101;
export const GITCG_ATTR_INIT_RANDOM_SEED = 102;
export const GITCG_ATTR_INIT_INITIAL_HANDS_COUNT = 103;
export const GITCG_ATTR_INIT_MAX_HANDS_COUNT = 104;
export const GITCG_ATTR_INIT_MAX_ROUNDS_COUNT = 105;
export const GITCG_ATTR_INIT_MAX_SUPPORTS_COUNT = 106;
export const GITCG_ATTR_INIT_MAX_SUMMONS_COUNT = 107;
export const GITCG_ATTR_INIT_INITIAL_DICE_COUNT = 108;
export const GITCG_ATTR_INIT_MAX_DICE_COUNT = 109;

export const GITCG_ATTR_INIT_NO_SHUFFLE_0 = 201;
export const GITCG_ATTR_INIT_NO_SHUFFLE_1 = 202;

export const GITCG_ATTR_INIT_DECK_CHARACTER_COUNT = 401;
export const GITCG_ATTR_INIT_DECK_CARD_COUNT = 402;

export const GITCG_ATTR_PLAYER_ALWAYS_OMNI = 301;
export const GITCG_ATTR_PLAYER_ALLOW_TUNING_ANY_DICE = 302;

export const GITCG_INTERNAL_IO_RPC = 1;
export const GITCG_INTERNAL_IO_NOTIFICATION = 2;
export const GITCG_INTERNAL_IO_ERROR = 3;
