on:
  push:

jobs:
  pyci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cbinding-library-*
          path: cbinding
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 12194329386
      - run: ls cbinding
